ElTrigal/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using ElTrigal.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ElTrigal.Controllers
{
    public class AccesoController : Controller
    {
        private readonly ElTrigalContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AccesoController(ElTrigalContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> DetailsCat(Guid? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }
        public IActionResult Catalogo()
        {
            var proveedores = _context.Proveedors.ToList() ?? new List<Proveedor>();

            ViewBag.Proveedores = proveedores;

            return View();
        }
        public IActionResult VerCatalogo(Guid id)
        {
            var proveedor = _context.Proveedors
                .Include(p => p.Marca)
                .ThenInclude(m => m.Productos)
                .ThenInclude(p => p.Categoria)
                .FirstOrDefault(p => p.Id == id);


            if (proveedor == null)
            {
                return NotFound();
            }

            var productos = proveedor.Marca.SelectMany(m => m.Productos).ToList();
            ViewBag.Productos = productos;

            var marcas = productos.Select(p => p.Marca).Distinct().ToList();
            ViewBag.Marcas = marcas;

            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Cotizacion()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cotizacion(string codigoCotizacion)
        {
            var cotizacion = _context.Cotizaciones.FirstOrDefault(c => c.CodigoFactura == codigoCotizacion);

            if (cotizacion == null)
            {
                ModelState.AddModelError("", "La cotización no fue encontrada.");
                return View();
            }

            return RedirectToAction("Details", new { id = cotizacion.Id });
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizaciones
                .Include(c => c.Cliente)
                .Include(c => c.Detalles)
                .ThenInclude(d => d.Producto)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cotizacion == null)
            {
                return NotFound();
            }

            decimal subTotal = cotizacion.Detalles.Sum(d => (d.Cantidad.HasValue ? d.Cantidad.Value : 0) * (d.Producto?.Precio ?? 0));
            decimal iva = cotizacion.Iva ? subTotal * 0.13m : 0;
            decimal total = subTotal + iva;

            ViewBag.SubTotal = subTotal;
            ViewBag.IVA = iva;
            ViewBag.Total = total;

            return View(cotizacion);
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(Usuario usuario)
        {
            var usuarioEncontrado = _context.Usuarios.SingleOrDefault(u => u.NameTag == usuario.NameTag);

            if (usuarioEncontrado != null && usuarioEncontrado.Pass == usuario.Pass)
            {
                var rolUsuario = _context.Roles.SingleOrDefault(r => r.Id == usuarioEncontrado.RolId);

                if (rolUsuario != null)
                {
                    RoleContext.CurrentRole = rolUsuario;

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Error al obtener el rol del usuario");
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", "Usuario o contraseña incorrectos");
                return View();
            }
        }

        private bool CotizacionExists(Guid id)
        {
            return _context.Cotizaciones.Any(e => e.Id == id);
        }
    }
}

ElTrigal/Controllers/InformesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElTrigal.Models;

namespace ElTrigal.Controllers
{
    public class InformesController : Controller
    {
        private readonly ElTrigalContext _context;

        public InformesController(ElTrigalContext context)
        {
            _context = context;
        }

        // GET: Informes
        public async Task<IActionResult> Index(DateTime? fecha, string tipoInforme)
        {
            IQueryable<Informe> informes = _context.InformesAnalises;

            if (fecha.HasValue)
            {
                informes = informes.Where(i => i.FechaGeneracion.Date == fecha.Value.Date);
            }

            if (!string.IsNullOrEmpty(tipoInforme))
            {
                informes = informes.Where(i => i.TipoInforme == tipoInforme);
            }

            return View(await informes.ToListAsync());
        }

        public async Task<IActionResult> FiltroPorFecha(DateTime fecha)
        {
            return RedirectToAction(nameof(Index), new { fecha = fecha.Date });
        }

        public async Task<IActionResult> FiltroPorTipo(string tipoInforme)
        {
            return RedirectToAction(nameof(Index), new { tipoInforme = tipoInforme });
        }

        private bool InformeExists(Guid id)
        {
          return (_context.InformesAnalises?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ElTrigal/Controllers/MarcasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElTrigal.Models;

namespace ElTrigal.Controllers
{
    public class MarcasController : Controller
    {
        private readonly ElTrigalContext _context;

        public MarcasController(ElTrigalContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var marcas = await _context.Marcas.Include(m => m.Proveedor).ToListAsync();
            return View(marcas);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .Include(m => m.Proveedor)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        public IActionResult Create()
        {
            ViewData["ProveedorId"] = new SelectList(_context.Proveedors, "Id", "Nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,ProveedorId,Descripcion,Especialidad")] Marca marca)
        {
            marca.Id = Guid.NewGuid();
            _context.Add(marca);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }
            ViewData["ProveedorId"] = new SelectList(_context.Proveedors, "Id", "Nombre", marca.ProveedorId);
            return View(marca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nombre,ProveedorId,Descripcion,Especialidad")] Marca marca)
        {
            if (id != marca.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(marca);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MarcaExists(marca.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .Include(m => m.Proveedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var marca = await _context.Marcas.FindAsync(id);
            if (marca != null)
            {
                _context.Marcas.Remove(marca);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(Guid id)
        {
            return _context.Marcas.Any(e => e.Id == id);
        }
    }
}

ElTrigal/Controllers/RolsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElTrigal.Models;

namespace ElTrigal.Controllers
{
    public class RolsController : Controller
    {
        private readonly ElTrigalContext _context;

        public RolsController(ElTrigalContext context)
        {
            _context = context;
        }

        // GET: Rols
        public async Task<IActionResult> Index()
        {
            return _context.Roles != null ?
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'ElTrigalContext.Roles'  is null.");
        }

        // GET: Rols/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // GET: Rols/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rols/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,VerTodo,VerUsuario,EditUsuario,EliUsuario,CrearUsuario,EditPass,VerCliente,EditCliente,EliCliente,CrearCliente,VerProveedor,EditProveedor,EliProveedor,CrearProveedor,VerMarca,EditMarca,EliMarca,CrearMarca,VerCategoria,EditCategoria,EliCategoria,CrearCategoria,VerProductos,EditProductos,EliProductos,Pedido,CrearProductos,VerCotizaciones,EditCotizaciones,EliCotizaciones,CrearCotizaciones,VerVentas,EditVentas,EliVentas,CrearVentas,VerRol,EditRol,EliRol,CrearRol,VerAnalisis")] Rol rol)
        {
                if (rol.EditPass)
                    rol.EditUsuario = true;

                if (rol.EditUsuario || rol.EliUsuario || rol.CrearUsuario)
                    rol.VerUsuario = true;

                if (rol.EditCliente || rol.EliCliente || rol.CrearCliente)
                    rol.VerCliente = true;

                if (rol.EditProveedor || rol.EliProveedor || rol.CrearProveedor)
                    rol.VerProveedor = true;

                if (rol.EditMarca || rol.EliMarca || rol.CrearMarca)
                    rol.VerMarca = true;

                if (rol.EditCategoria || rol.EliCategoria || rol.CrearCategoria)
                    rol.VerCategoria = true;

                if (rol.EditProductos || rol.EliProductos || rol.CrearProductos || rol.Pedido || rol.VerCatalogo)
                    rol.VerProductos = true;

                if (rol.EditCotizaciones || rol.EliCotizaciones || rol.CrearCotizaciones)
                    rol.VerCotizaciones = true;

                if (rol.EditVentas || rol.EliVentas || rol.CrearVentas)
                    rol.VerVentas = true;

                if (rol.EditRol || rol.EliRol || rol.CrearRol)
                    rol.VerRol = true;
          
            rol.Id = Guid.NewGuid();
                _context.Add(rol);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

        // GET: Rols/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles.FindAsync(id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nombre,VerTodo,VerUsuario,EditUsuario,EliUsuario,CrearUsuario,EditPass,VerCliente,EditCliente,EliCliente,CrearCliente,VerProveedor,EditProveedor,EliProveedor,CrearProveedor,VerMarca,EditMarca,EliMarca,CrearMarca,VerCategoria,EditCategoria,EliCategoria,CrearCategoria,VerProductos,EditProductos,EliProductos,CrearProductos,VerCotizaciones,EditCotizaciones,EliCotizaciones,CrearCotizaciones,VerVentas,EditVentas,EliVentas,CrearVentas,VerRol,EditRol,EliRol,CrearRol,VerAnalisis")] Rol rol)
        {
            if (id != rol.Id)
            {
                return NotFound();
            }

            if (rol.EditPass)
                rol.EditUsuario = true;

            if (rol.EditUsuario || rol.EliUsuario || rol.CrearUsuario)
                rol.VerUsuario = true;

            if (rol.EditCliente || rol.EliCliente || rol.CrearCliente)
                rol.VerCliente = true;

            if (rol.EditProveedor || rol.EliProveedor || rol.CrearProveedor)
                rol.VerProveedor = true;

            if (rol.EditMarca || rol.EliMarca || rol.CrearMarca)
                rol.VerMarca = true;

            if (rol.EditCategoria || rol.EliCategoria || rol.CrearCategoria)
                rol.VerCategoria = true;

            if (rol.EditProductos || rol.EliProductos || rol.CrearProductos || rol.Pedido || rol.VerCatalogo)
                rol.VerProductos = true;

            if (rol.EditCotizaciones || rol.EliCotizaciones || rol.CrearCotizaciones)
                rol.VerCotizaciones = true;

            if (rol.EditVentas || rol.EliVentas || rol.CrearVentas)
                rol.VerVentas = true;

            if (rol.EditRol || rol.EliRol || rol.CrearRol)
                rol.VerRol = true;


            try
            {
                _context.Update(rol);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RolExists(rol.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Rols/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var rol = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // POST: Rols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'ElTrigalContext.Roles'  is null.");
            }
            var rol = await _context.Roles.FindAsync(id);
            if (rol != null)
            {
                _context.Roles.Remove(rol);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RolExists(Guid id)
        {
            return (_context.Roles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ElTrigal/Views/Home/Details.cshtml
@model ElTrigal.Models.Producto

@{
    ViewData["Title"] = "Detalles del Producto";
    Layout = null;
}

<link rel="stylesheet" href="~/css/productos.css">
@if (RoleContext.CurrentRole != null && !RoleContext.CurrentRole.VerProductos)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}
<h1>Detalles del Producto</h1>

<div>
    <h2>
        @Html.DisplayFor(model => model.Nombre)
    </h2>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <td>Código</td>
                <td>Marca</td>
                <td>Categoría</td>
                <td>Cantidad</td>
                <td>Precio</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.Codigo)</td>
                <td>@Html.DisplayFor(model => model.Marca.Nombre)</td>
                <td>@Html.DisplayFor(model => model.Categoria.Nombre)</td>
                <td>@Html.DisplayFor(model => model.Cantidad)</td>
                <td>@Html.DisplayFor(model => model.Precio) @Html.DisplayFor(model => model.Ventas)</td>
            </tr>
            <tr>
                <td colspan="5" style="text-align:center;">Descripción</td>
            </tr>
            <tr>
                <td colspan="5" style="text-align:center;">@Html.DisplayFor(model => model.Descripcion)</td>
            </tr>
        </tbody>
    </table>

</div>
<div>
    <a asp-action="Index">Regresar al Listado</a>
</div>

ElTrigal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Principal";
    Layout = null;
}

    @if (RoleContext.CurrentRole != null && !RoleContext.CurrentRole.VerTodo)
    {
        <script>window.location.href = '@Url.Action("Index", "Acceso")';</script>
    }

<link rel="stylesheet" href="~/css/index.css">

@model List<Producto>

    <h1>El Trigal</h1>
<div class="container">
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerCotizaciones || RoleContext.CurrentRole.VerVentas || RoleContext.CurrentRole.VerAnalisis))
    {
        <a class="nav-link cotizaciones @(RoleContext.CurrentRole.VerProductos ? "" : "dentro")" asp-action="Ventas">Ventas</a>
    }

    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerUsuario == true || RoleContext.CurrentRole.VerCliente == true || RoleContext.CurrentRole.VerRol == true))
    {
        <a class="nav-link personas @(RoleContext.CurrentRole.VerProductos ? "" : "dentro")" asp-action="Personas">Personas</a>
    }

    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerProductos || RoleContext.CurrentRole.VerCategoria || RoleContext.CurrentRole.VerMarca || RoleContext.CurrentRole.VerProveedor))
    {
        <a class="nav-link productos @(RoleContext.CurrentRole.VerProductos ? "" : "dentro")" asp-action="Productos">Productos</a>
    }

    @if (RoleContext.CurrentRole != null)
    {
        <a class="nav-link salir @(RoleContext.CurrentRole.VerProductos ? "" : "dentro")" asp-action="Index" asp-controller="Acceso">Salir</a>
    }

</div>

 @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerProductos == true))
{
    <form asp-action="Filtro" method="get">
        <div class="filter-container">
            <div class="table-container">
            <table class="table invisible" style="border: 0;">
                <thead>
                    <tr>
                        <th style="background-color: #1a1a1a; border:0;" colspan="2"><label for="Codigo">Codigo:</label></th>
                        <th style="background-color: #1a1a1a; border:0;" colspan="2"><label for="nombre">Nombre:</label></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="background-color: #1a1a1a; border:0;" colspan="2"><input type="text" id="codigo" name="codigo" value="@ViewBag.Codigo" /></td>
                        <td style="background-color: #1a1a1a; border:0;" colspan="2"><input type="text" id="nombre" name="nombre" value="@ViewBag.Nombre" /></td>
                    </tr>
                </tbody>
            </table>
            <table class="table invisible" style="border: 0;">
                <thead>
                    <tr>
                        <th style="background-color: #1a1a1a; border:0;" colspan="2"><label for="nombre">Proveedor:</label></th>
                        <th style="background-color: #1a1a1a; border:0;" colspan="2"><label for="nombre">Marca:</label></th>
                        <th style="background-color: #1a1a1a; border:0;" colspan="2"><label for="nombre">Categoria:</label></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="background-color: #1a1a1a; border:0;" colspan="2">
                            <select id="proveedor" name="proveedor">
                                <option value="">Todos</option>
                                @if (ViewBag.Proveedores != null)
                                {
                                    foreach (var proveedor in ViewBag.Proveedores)
                                    {
                                        <option value="@proveedor.Id">@proveedor.Nombre</option>
                                    }
                                }
                            </select>
                        </td>
                        <td style="background-color: #1a1a1a; border:0;" colspan="2">
                            <select id="marca" name="marca">
                                <option value="">Todas</option>
                                @if (ViewBag.Marcas != null)
                                {
                                    foreach (var marca in ViewBag.Marcas)
                                    {
                                        <option value="@marca.Id">@marca.Nombre</option>
                                    }
                                }

                            </select>
                        </td>
                        <td style="background-color: #1a1a1a; border:0;" colspan="2">
                            <select id="categoria" name="categoria">
                                <option value="">Todas</option>
                                @if (ViewBag.Categorias != null)
                                {
                                    foreach (var categoria in ViewBag.Categorias)
                                    {
                                        <option value="@categoria.Id">@categoria.Nombre</option>
                                        <p value="@categoria.Descripcion"></p>
                                    }
                                }
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
            <input type="submit" value="Filtrar (@Model.Count)" />
        </div>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Proveedor</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th>Detalles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Codigo</td>
                    <td>@item.Nombre</td>
                    <td>@item.Marca?.Nombre</td>
                    <td>@item.Marca?.Proveedor?.Nombre</td>
                    <td>@item.Categoria?.Nombre</td>
                    <td>$@Math.Round(item.Precio ?? 0, 2) @item.Ventas</td>
                    <td><a asp-action="Details" asp-route-id="@item.Id" class="ver">Ver</a></td>
                </tr>
            }
        </tbody>
</table>
}

ElTrigal/Views/Home/Personas.cshtml
@{
    ViewData["Title"] = "Personas";
    Layout = null;
}

@if (RoleContext.CurrentRole == null || !(RoleContext.CurrentRole.VerUsuario || RoleContext.CurrentRole.VerCliente || RoleContext.CurrentRole.VerRol))
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}

<link rel="stylesheet" href="~/css/index.css">
<h3>Personas</h3>
<div class="container">
    @if (RoleContext.CurrentRole.VerUsuario)
    {
        <a class="nav-link personas dentro" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
    }
    @if (RoleContext.CurrentRole.VerCliente)
    {
        <a class="nav-link personas dentro" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
    }
    @if (RoleContext.CurrentRole.VerRol)
    {
        <a class="nav-link personas dentro" asp-area="" asp-controller="Rols" asp-action="Index">Roles</a>
    }
    <a class="nav-link text-dark salir dentro" asp-area="" asp-controller="Home" asp-action="Index">Volver</a>
</div>

<p>
    En esta parte puedes ver todo lo relacionado a personas, como los <b>Clientes</b> para cotizaciones y ventas,
    y los propios <b>Usuarios</b> que pueden usar este sistema y los <b>Roles</b> de los Usuarios
</p>

ElTrigal/Views/Home/Productos.cshtml
@{
    ViewData["Title"] = "Productos";
    Layout = null;
}
<link rel="stylesheet" href="~/css/index.css">
<div class="container">
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerProductos == true))
    {
        <a class="nav-link productos dentro" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
    }
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerMarca == true))
    {
        <a class="nav-link productos dentro" asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a>
    }
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerProveedor == true))
    {
        <a class="nav-link productos dentro" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedor</a>
    }
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerCategoria == true))
    {
        <a class="nav-link productos dentro" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
    }
    <a class="nav-link text-dark salir dentro" asp-area="" asp-controller="Home" asp-action="Index">Volver</a>
</div>

<p>
    Aca puedes ver todo lo relacionado a los productos, como las <b>Marcas</b> y sus <b>Proveedores</b>, las <b>Categorias</b>
    de los productos y los propios <b>Productos</b>
</p>

ElTrigal/Views/Home/Ventas.cshtml
@{
    ViewData["Title"] = "Ventas";
    Layout = null;
}
<link rel="stylesheet" href="~/css/index.css">
<div class="container">
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerCotizaciones == true))
    {
        <a class="nav-link cotizaciones dentro" asp-controller="Cotizacions" asp-action="Index">Cotizaciones</a>
    }
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerVentas == true))
    {
        <a class="nav-link cotizaciones dentro" asp-controller="Ventas" asp-action="Index">Ventas</a>
    }
    @if (RoleContext.CurrentRole != null && (RoleContext.CurrentRole.VerAnalisis == true))
    {
        <a class="nav-link cotizaciones dentro" asp-controller="Informes" asp-action="Index">Informes</a>
    }
    <a class="nav-link text-dark salir dentro" asp-area="" asp-controller="Home" asp-action="Index">Volver</a>
</div>


<p>
    En esta parte se puede crear las <b>Cotizaciones</b> y <b>Ventas</b> para los <b>Clientes</b>
    tambien se pueden ver los <b>Informes</b> para ver los movimientos del <b>Producto</b>
</p>