ElTrigal/Models/Cotizacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ElTrigal.Models;

public partial class Cotizacion
{

    [DisplayName("Codigo de Factura")]
    public string? CodigoFactura { get; set; }

    [DisplayName("Codigo de Pedido")]
    public string? CodigoPedido { get; set; }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [DisplayName("Cliente")]
    public Guid? ClienteId { get; set; }

    [DisplayName("Fecha de Creacion")]
    [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}", ApplyFormatInEditMode = true)]
    public DateTime Fecha { get; set; }

    [DisplayName("Fecha de Vencimiento")]
    [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}", ApplyFormatInEditMode = true)]
    public DateTime Vencimiento { get; set; }

    [DisplayName("Entregado")]
    public bool Entregado { get; set; }

    [DisplayName("Con IVA")]
    public bool Iva { get; set; }

    [DisplayName("Comentarios")]
    public string? Comentario { get; set; }

    [DisplayName("Pagado")]
    public bool Pagado { get; set; }

    [DisplayName("Cantidad Abonada")]
    public decimal? Abono { get; set; }

    [NotMapped]
    public int Dias { get; set; }

    public Cliente? Cliente { get; set; }

    public List<Detalle> Detalles { get; set; }
}

ElTrigal/Controllers/CotizacionsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElTrigal.Models;

namespace ElTrigal.Controllers
{
    public class CotizacionsController : Controller
    {
        private readonly ElTrigalContext _context;

        public CotizacionsController(ElTrigalContext context)
        {
            _context = context;
        }

        // GET: Cotizacions
        public async Task<IActionResult> Index(string codigoFactura, DateTime? fechaDespuesDe, DateTime? fechaAntesDe)
        {
            var cotizaciones = await Filtro(codigoFactura, fechaDespuesDe, fechaAntesDe);

            ViewData["CodigoFactura"] = codigoFactura;
            ViewData["FechaDespuesDe"] = fechaDespuesDe;
            ViewData["FechaAntesDe"] = fechaAntesDe;

            return View(cotizaciones);
        }

        private async Task<List<Cotizacion>> Filtro(string codigoFactura, DateTime? fechaDespuesDe, DateTime? fechaAntesDe)
        {
            var cotizaciones = from c in _context.Cotizaciones.Include(c => c.Cliente)
                               select c;

            if (!String.IsNullOrEmpty(codigoFactura))
            {
                cotizaciones = cotizaciones.Where(c => c.CodigoFactura.Contains(codigoFactura));
            }

            if (fechaDespuesDe != null)
            {
                cotizaciones = cotizaciones.Where(c => c.Fecha >= fechaDespuesDe);
            }

            if (fechaAntesDe != null)
            {
                cotizaciones = cotizaciones.Where(c => c.Fecha <= fechaAntesDe);
            }

            return await cotizaciones.ToListAsync();
        }



        // GET: Cotizacions/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizaciones
                .Include(c => c.Cliente)
                .Include(c => c.Detalles)
                .ThenInclude(d => d.Producto)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cotizacion == null)
            {
                return NotFound();
            }

            decimal subTotal = cotizacion.Detalles.Sum(d => (d.Cantidad.HasValue ? d.Cantidad.Value : 0) * (d.Producto?.Precio ?? 0));
            decimal iva = cotizacion.Iva ? subTotal * 0.13m : 0;
            decimal total = subTotal + iva;

            ViewBag.SubTotal = subTotal;
            ViewBag.IVA = iva;
            ViewBag.Total = total;

            return View(cotizacion);
        }

        // GET: Cotizacions/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre");
            return View();
        }

        // POST: Cotizacions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,Iva,Dias,Entregado,Comentario,Pagado,Abono")] Cotizacion cotizacion)
        {
            cotizacion.CodigoPedido = GenerateUniqueRandomNumericString(7);
            cotizacion.CodigoFactura = GenerateUniqueRandomNumericString(8);
            cotizacion.Id = Guid.NewGuid();
            cotizacion.Fecha = DateTime.Now;
            cotizacion.Vencimiento = cotizacion.Fecha.AddDays(cotizacion.Dias);
            cotizacion.Entregado = false;
            cotizacion.Pagado = false;
            cotizacion.Abono ??= 0.00m;

            var nuevoInforme = new Informe

            {
                Id = Guid.NewGuid(),
                TipoInforme = "Cotización",
                DetallesInforme = $"Se creo la cotizacion con el codigo de factura {cotizacion.CodigoFactura} para el cliente {cotizacion.Cliente?.Nombre}",
                FechaGeneracion = DateTime.Now
            };

            _context.Add(nuevoInforme);
            _context.Add(cotizacion);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Detalles", new { perteneceId = cotizacion.Id });
        }

        private string GenerateUniqueRandomNumericString(int length)
        {
            Random random = new Random();
            const string chars = "0123456789";
            string randomString;

            do
            {
                randomString = new string(Enumerable.Repeat(chars, length)
                    .Select(s => s[random.Next(s.Length)]).ToArray());
            }
            while (IsCodeExists(randomString));

            return randomString;
        }

        private bool IsCodeExists(string code)
        {
            return _context.Cotizaciones.Any(c => c.CodigoPedido == code || c.CodigoFactura == code);
        }


        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizaciones.FindAsync(id);
            if (cotizacion == null)
            {
                return NotFound();
            }

            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", cotizacion.ClienteId);

            return View(cotizacion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ClienteId,Iva,Dias,Entregado,Comentario,Pagado,Abono")] Cotizacion cotizacion)
        {
            try
            {
                if (id != cotizacion.Id)
                {
                    return NotFound();
                }

                var cotizacionOriginal = await _context.Cotizaciones.FindAsync(id);
                if (cotizacionOriginal == null)
                {
                    return NotFound();
                }

                cotizacionOriginal.ClienteId = cotizacion.ClienteId;
                cotizacionOriginal.Iva = cotizacion.Iva;
                cotizacionOriginal.Entregado = cotizacion.Entregado;
                cotizacionOriginal.Comentario = cotizacion.Comentario;
                cotizacionOriginal.Pagado = cotizacion.Pagado;
                cotizacionOriginal.Abono = cotizacion.Abono;

                cotizacionOriginal.Vencimiento = cotizacionOriginal.Fecha.AddDays(cotizacion.Dias);

                _context.Entry(cotizacionOriginal).State = EntityState.Modified;

                var nuevoInforme = new Informe
                {
                    Id = Guid.NewGuid(),
                    TipoInforme = "Cotización",
                    DetallesInforme = $"Se actualizó la cotización con el código de factura {cotizacion.CodigoFactura} para el cliente {cotizacion.Cliente?.Nombre}",
                    FechaGeneracion = DateTime.Now
                };

                _context.Add(nuevoInforme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error al editar la cotización: {ex.Message}");
                return View(cotizacion);
            }
        }

        // GET: Cotizacions/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizaciones
                .Include(c => c.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cotizacion == null)
            {
                return NotFound();
            }

            return View(cotizacion);
        }

        // POST: Cotizacions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cotizacion = await _context.Cotizaciones.FindAsync(id);
            if (cotizacion == null)
            {
                return NotFound();
            }

            _context.Cotizaciones.Remove(cotizacion);

            var nuevoInforme = new Informe
            {
                Id = Guid.NewGuid(),
                TipoInforme = "Cotización",
                DetallesInforme = $"Se eliminó la cotización con el código de factura {cotizacion.CodigoFactura} para el cliente {cotizacion.Cliente?.Nombre}",
                FechaGeneracion = DateTime.Now
            };

            _context.Add(nuevoInforme);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CotizacionExists(Guid id)
        {
            return _context.Cotizaciones.Any(e => e.Id == id);
        }
    }
}

ElTrigal/Views/Cotizacions/Create.cshtml
@model ElTrigal.Models.Cotizacion

@{
    ViewData["Title"] = "Create";
    Layout = null;
}
@if (RoleContext.CurrentRole == null || !RoleContext.CurrentRole.CrearCotizaciones)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}

<link rel="stylesheet" href="~/css/cotizacion.css">

<h1>Create</h1>

<h4>Cotizacion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId">
                    <option value="">-- Selecciona un cliente --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Iva" class="control-label"></label>
                <select asp-for="Iva" class="form-control">
                    <option value="true">Con IVA</option>
                    <option value="false">Sin IVA</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Dias" class="control-label"></label>
                <select asp-for="Dias" class="form-control">
                    <option value="7">7 Días</option>
                    <option value="15">15 Días</option>
                    <option value="30">Un mes</option>
                    <option value="60">Dos meses</option>
                    <option value="90">Tres meses</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Añadir Productos" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al Listado</a>
</div>

ElTrigal/Views/Cotizacions/Delete.cshtml
@model ElTrigal.Models.Cotizacion

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}
@if (RoleContext.CurrentRole == null || !RoleContext.CurrentRole.EliCotizaciones)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}

<link rel="stylesheet" href="~/css/cotizacion.css">


<h1>Borrar</h1>

<h3>¿Estas seguro de querer eliminar esta Cotizacion?</h3>
<div>
    <h4>Cotizacion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vencimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vencimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Entregado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Entregado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Iva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Iva)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pagado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-primary" style="width:20%;" />
        <a asp-action="Index">Cancelar</a>
    </form>
</div>

ElTrigal/Views/Cotizacions/Details.cshtml
@model ElTrigal.Models.Cotizacion

@{
    ViewData["Title"] = "Details";
    Layout = null;
}
@if (RoleContext.CurrentRole == null || !RoleContext.CurrentRole.VerCotizaciones)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}

<link rel="stylesheet" href="~/css/cotizacion.css">

<div>
    <hr />
    <table class="table invisible" style="border: 0;">
        <thead>
            <tr>
            <tr>
                <th style="background-color: #1a1a1a; font-size:30px;" colspan=" 5">Agro Ferreteria "El Trigal"</th>
            </tr>
            <tr>
                <th style="background-color: #1a1a1a;" colspan="3">Direccion</th>

                <th style="background-color: #1a1a1a;">Telefono</th>

                <th style="background-color: #1a1a1a;">Razon Social</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="background-color: #1a1a1a;">La LIbertad</td>

                <td style="background-color: #1a1a1a;">Ciudad Arce</td>

                <td style="background-color: #1a1a1a;">Av. Masferrer, Casa #2</td>

                <td style="background-color: #1a1a1a;">(+503)7743-7365</td>

                <td style="background-color: #1a1a1a;">Mario Argumedo</td>
            </tr>
        </tbody>
    </table>

    <table class="table invisible" style="border: 0;">
        <thead>
            <tr>
            <tr>
                <th style="background-color: #1a1a1a; font-size:30px;" colspan="6">@Html.DisplayFor(model => model.Cliente.Nombre)</th>
            </tr>
            <tr>
                <th style="background-color: #1a1a1a;">@Html.DisplayNameFor(model => model.Cliente.Dui)</th>

                <th style="background-color: #1a1a1a;">@Html.DisplayNameFor(model => model.Cliente.Telefono)</th>

                <th style="background-color: #1a1a1a;">@Html.DisplayNameFor(model => model.Cliente.Correo)</th>

                <th style="background-color: #1a1a1a;" colspan=" 3">Direccion</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Dui)</td>
            
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Telefono)</td>
            
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Correo)</td>
            
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Departamento)</td>
            
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Municipio)</td>
            
                <td style="background-color: #1a1a1a;">@Html.DisplayFor(model => model.Cliente.Direccion)</td>
            </tr>
        </tbody>
    </table>
</div>

<div>
    <hr />
    <table class="table invisible" style="border: 0;">
        <thead>
            <tr>
            <tr>
                <th style="background-color: #1a1a1a; font-size:30px; border: 0;" colspan=" 6">Cotizacion @Html.DisplayFor(model => model.CodigoFactura)</th>
            </tr>
            <tr>
                <th style="background-color: #1a1a1a; border: 0;">@Html.DisplayNameFor(model => model.Fecha)</th>

                <th style="background-color: #1a1a1a; border: 0;">@Html.DisplayNameFor(model => model.Vencimiento)</th>

                <th style="background-color: #1a1a1a; border: 0;">Estado</th>

                <th style="background-color: #1a1a1a; border: 0;">¿Tiene IVA?</th>

                <th style="background-color: #1a1a1a; border: 0;">Pago</th>

                <th style="background-color: #1a1a1a; border: 0;">Cantidad Abonada</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Fecha)</td>

                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Vencimiento)</td>

                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Entregado)</td>

                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Iva)</td>

                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Pagado)</td>

                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Abono)</td>
            </tr>
        </tbody>
    </table>
</div>
<link rel="stylesheet" href="~/css/cotizacion.css">
<div>
    <hr/>
    <h2>Detalles  @Html.DisplayFor(model => model.CodigoPedido)</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Unidad</th>
                <th>Precio Unitario</th>
                <th>Descuento</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var detalle in Model.Detalles)
            {
                <tr>
                    <td>@detalle.Producto?.Codigo</td>
                    <td>@detalle.Producto?.Nombre</td>
                    <td>@detalle.Cantidad</td>
                    <td>@detalle.Producto?.Ventas</td>
                    <td>@String.Format("{0:C}", Math.Round(detalle.Producto?.Precio ?? 0, 2))</td>
                    <td>@detalle.Descuento%</td>
                    <td>@String.Format("{0:C}", Math.Round(((detalle.Cantidad * (detalle.Producto?.Precio ?? 0)) - ((detalle.Cantidad * (detalle.Producto?.Precio ?? 0)) * (detalle.Descuento / 100))) ?? 0, 2))</td>
                </tr>
            }
        </tbody>
        <tfoot style="border: 0;">
            <tr>
                <td colspan="5" style="background-color: #1a1a1a; border: 0; "></td>
                <td style="background-color: #1a1a1a; border: 0; text-align: right;"><strong>SubTotal:</strong></td>
                <td>@String.Format("{0:C}", Math.Round(ViewBag.SubTotal, 2))</td>
            </tr>
            <tr>
                <td colspan="5" style="background-color: #1a1a1a; border: 0; "></td>
                <td style="background-color: #1a1a1a; border: 0; text-align: right;"><strong>IVA:</strong></td>
                <td>@String.Format("{0:C}", Math.Round(ViewBag.IVA, 2))</td>
            </tr>
            <tr>
                <td colspan="5" style="background-color: #1a1a1a; border: 0; "></td>
                <td style="background-color: #1a1a1a; border: 0; text-align: right;"><strong>Total:</strong></td>
                <td>@String.Format("{0:C}", Math.Round(ViewBag.Total, 2))</td>
            </tr>
        </tfoot>
    </table>
</div>

<div>
    <table class="table invisible" style="border: 0;">
    <thead>
        <tr>
        <tr>
                <th style="background-color: #1a1a1a; border: 0;">@Html.DisplayNameFor(model => model.Comentario)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
                <td style="background-color: #1a1a1a; border: 0;">@Html.DisplayFor(model => model.Comentario)</td>
        </tr>
    </tbody>
</table>
</div>
<div>
    @if (RoleContext.CurrentRole == null || !RoleContext.CurrentRole.EditCotizaciones)
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="editar">Editar</a>
    }
    <a asp-action="Index" class="ver">Regresar al Listado</a>
</div>

ElTrigal/Views/Cotizacions/Edit.cshtml
@model ElTrigal.Models.Cotizacion

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}
@if (RoleContext.CurrentRole != null && !RoleContext.CurrentRole.EditCotizaciones)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}
<link rel="stylesheet" href="~/css/cotizacion.css">


<h1>Edit</h1>

<h4>Cotizacion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dias" class="control-label"></label>
                <select asp-for="Dias" class="form-control">
                    <option value="7">Una semana</option>
                    <option value="15">15 días</option>
                    <option value="30">Un mes</option>
                    <option value="60">Dos meses</option>
                    <option value="90">Tres meses</option>
                </select>
                <span asp-validation-for="Dias" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Entregado" /> @Html.DisplayNameFor(model => model.Entregado)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Iva" /> @Html.DisplayNameFor(model => model.Iva)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pagado" /> @Html.DisplayNameFor(model => model.Pagado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Abono" class="control-label"></label>
                <input asp-for="Abono" class="form-control" />
                <span asp-validation-for="Abono" class="text-danger"></span>
            </div>

                <a asp-controller="Detalles" asp-action="Index" asp-route-perteneceId="@Model.Id">Editar Productos</a>
           
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al Listado</a>
</div>

ElTrigal/Views/Cotizacions/Index.cshtml
@model IEnumerable<ElTrigal.Models.Cotizacion>

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
@if (RoleContext.CurrentRole != null && !RoleContext.CurrentRole.VerCotizaciones)
{
    <script>window.location.href = '@Url.Action("Index", "Home")';</script>
}
<link rel="stylesheet" href="~/css/cotizacion.css">

<h1>Cotizaciones</h1>

<hr />
<p>
    @if (RoleContext.CurrentRole != null && RoleContext.CurrentRole.CrearCotizaciones)
    {
        <a asp-action="Create" class="crear">Añadir Cotización</a>
    }
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Volver</a>
</p>

<form method="get" action="@Url.Action("Index", "Cotizacions")" class="form-inline">
    <table style="align-items:center;">
        <thead>
            <tr>
                <th>Código de Factura</th>
                <th>Creada después del</th>
                <th>Creada antes del</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="text" id="codigoFactura" name="codigoFactura" value="@ViewData["CodigoFactura"]" class="form-control" /></td>
                <td>
                    <input type="date" id="fechaDespuesDe" name="fechaDespuesDe" value="@ViewData["FechaDespuesDe"]" class="form-control" />
                </td>
                <td>
                    <input type="date" id="fechaAntesDe" name="fechaAntesDe" value="@ViewData["FechaAntesDe"]" class="form-control" />
                </td>
            </tr>
        </tbody>
        <tfoot>
        <td colspan="3"><button type="submit" class="btn btn-primary">Buscar</button></td>
        </tfoot>
    </table>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodigoFactura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vencimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CodigoFactura)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Nombre)
            </td>
            <td>
                    @if (RoleContext.CurrentRole != null && RoleContext.CurrentRole.EditCotizaciones)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="editar">Editar</a>
                    }
                    @if (RoleContext.CurrentRole != null && RoleContext.CurrentRole.VerCotizaciones)
                    {
                        <a asp-action="Details" asp-route-id="@item.Id" class="ver">Ver</a>
                    }
                    @if (RoleContext.CurrentRole != null && RoleContext.CurrentRole.EliCotizaciones)
                    {
                        <a asp-action="Delete" asp-route-id="@item.Id" class="borrar">Borrar</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>